- .vscode/settings.json
leveraging the [ymotongpoo/vsc-licenser](https://github.com/ymotongpoo/vsc-licenser) extension.
I wasn't sure if we wanted this to be committed since it is `IDE` specific,
but I thought that I would at least open up the discussion.
> Setup license header for VS Code users

- cohort-engine/src/main/java/com/ibm/cohort/engine/CqlEngineWrapper.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/translation/BaseCqlTranslationProvider.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/translation/CqlTranslationProvider.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/translation/InJVMCqlTranslationProvider.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/CqlEngineWrapperTest.java
- cohort-engine/src/test/resources/cql/ig-test/test.cql
- cohort-engine/src/test/resources/modelinfo/ig-with-target-modelinfo-0.0.1.xml
~I originally had code where I was passing around the model info information so it would be available in the `InJVMCqlTranslationProvider`. That started to make the code pretty clunky having to modify function calls along the way, so I instead took a page out of the cql translator's book and just register a model info provider directly from `runWithArgs`.~
Edit: Code wound up in a middle ground after a couple revisions. Not quite the same place as the starting place described above.
I added a fake IG and a test CQL written against the IG. The fake IG is base FHIR + a single `FakePatient` resource I added. `FakePatient` has one custom extension called `fakeExtension`.
The test CQL references the `FakePatient` and its custom extension. I was somewhat lazy with the test, since the main thing …
> Model info support

- docs/README.md
- docs/index.html
Noticed a couple places pointing at the old repo
> Update links for the open repo

- cohort-engine/src/main/java/com/ibm/cohort/engine/FhirLibraryLibrarySourceProvider.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/LibraryFormat.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/LibraryHelper.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/LibraryLoader.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/BaseFhirTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/FhirLibraryLibrarySourceProviderTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/MeasureEvaluatorTest.java
Jeff noted that Library resources were being uploaded with CQL/ELM content being Base64-encoded twice. This PR updates the evaluation code to remove all the places where were forcing Base64 decoding. Kwas updated the test resources in a separate changeset.
> Remove forced Base64 decoding of attachment data

- .github/workflows/buildJava11.yml
- cohort-engine-api-web/pom.xml
Updated powermockito dependency to 2.0.9. The automatic build in this repo succeeded for Java 8: https://github.com/Alvearie/quality-measure-and-cohort-service/actions/runs/408767077
I forked this repo and set up a build with Java 11 in the fork. Before the dependency update I was getting the same error Jai was hitting when building with Java 11: https://github.com/msargentibm/quality-measure-and-cohort-service/runs/1501344501?check_suite_focus=true#step:5:38631
With the dependency update, the Java 11 build succeeds: https://github.com/msargentibm/quality-measure-and-cohort-service/runs/1518725388?check_suite_focus=true
> Update powermockito to 2.0.9

- .gitattributes
I  would need help  from folks running Windows to test this out, but this configuration might help avoid CRLF line endings that were making the docker build and run for the tests project fail.
https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings
Edit: Just tested this out with Jai. Confirmed that:
* Windows was switching line endings to CRLF on the main branch.
* Windows leaves the line endings as LF with these changes.
> Force line feed endings for bash scripts

- cohort-parent/pom.xml
Took the cautious route. Added in dependencies until everything with a hapi- prefix in the dependency tree was on version 5.2.0.
> Lock in hapi dependencies to 5.2.0

- cohort-engine/src/main/java/com/ibm/cohort/engine/LibraryUtils.java
The error message that gets thrown when expected library parameters are
not provided is supposed to include the name of those missing
parameters, but the corresponding *format specifier* is missing.
This commit simply adds it.
Before:
```
Loading libraries from ZIP 'C:\Users\LuisGarcia\Downloads\CMS645v2.zip'
[main] INFO ca.uhn.fhir.context.FhirContext - Creating new FHIR context
for FHIR version [R4]
Exception in thread "main" java.lang.IllegalArgumentException: Missing
parameter values for one or more non-default library parameters: {}
```
After:
```
Loading libraries from ZIP 'C:\Users\LuisGarcia\Downloads\CMS645v2.zip'
[main] INFO ca.uhn.fhir.context.FhirContext - Creating new FHIR context
for FHIR version [R4]
Exception in thread "main" java.lang.IllegalArgumentException: Missing …
```
> Fix error message String format

- cohort-cli/src/main/java/com/ibm/cohort/cli/CohortCLI.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/EvaluateMeasureResults.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/EvaluateMeasuresStatus.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/MeasuresEvaluation.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/PatientMeasureEvaluationGroup.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/PatientMeasureEvaluationGroupStratifier.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/PatientMeasureEvaluationGroupStratifierStratum.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/PatientMeasureEvaluationGroupStratifierStratumComponent.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/PatientMeasureEvaluationPeriod.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/PatientMeasureEvaluationPopulation.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/PatientMeasureEvaluationQuantity.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/PatientMeasureEvaluations.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/VersionedMeasures.java
- cohort-engine/pom.xml
- cohort-engine/src/main/java/com/ibm/cohort/engine/CqlEngineWrapper.java
- cohort-parent/pom.xml
- fhir-client-config/src/main/java/com/ibm/cohort/fhir/client/config/FhirClientBuilderFactory.java
- tests/src/main/java/com/ibm/cohort/engine/test/TestWrapper.java
This looks like a lot of changes, but it's just cleaning up javadoc warnings.  I added a comment to the pom that was the only significant change.
Possibly contentious: I added javadoc generation to the maven jar phase, so that people would catch this building locally (and not have to run site or javadoc commands.
Probably contentious: I made javadoc warnings fail the build.  I did this first so I could catch them and clean them up, but after thinking about it decided that it made sense to keep our javadoc as clean as possible.  If there is a preference for me to remove this, will do so.
> Adding Javadoc

- cohort-cli/src/test/java/com/ibm/cohort/cli/CohortCLITest.java
- cohort-cli/src/test/java/com/ibm/cohort/cli/MeasureCLITest.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/LibraryHelper.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/seed/MeasureEvaluationSeeder.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/BaseFhirTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/LibraryHelperTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/BaseMeasureTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/MeasureEvaluatorTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/MeasureHelperTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/RestFhirLibraryResolutionProviderTest.java
- cohort-engine/src/test/resources/cql/fhir-measure-nested-libraries/test-child.cql
- cohort-engine/src/test/resources/cql/fhir-measure-nested-libraries/test-nested-child.cql
- cohort-engine/src/test/resources/cql/fhir-measure-nested-libraries/test-parent.cql
The Library loading mechanism provided through the cqf-ruler requires that Measure.library references use ID-based retrieval vs. understanding canonical URLs appropriately for Library.url based retrieval. This PR updates the library loading mechanism with support for canonical URL resolution in addition to the resource ID based retreival. Additionally, the default mechanism would load a Measure and its direct Library dependencies, but would not traverse transitive dependencies. This PR adds a recursive tree-walk for library loading and includes cycle detection to prevent infinite loops during library loading.
> Update Library loading mechanism for canonical URLs

- cohort-engine/src/test/java/com/ibm/cohort/engine/BasePatientTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/CqlEngineWrapperTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/DefaultFilenameToVersionedIdentifierStrategyTest.java
- cohort-engine/src/test/resources/cql/uomequivalence/TestUOMCompare-1.0.0.cql
This is a follow-up to the conversation I started with our team related to units of measure and quantity comparison in the CQL engine. I added a test case to the CqlEngineWrapperTest that documents the existing behavior for direct equals comparison of two quantities with different UoMs, comparison where one quantity is converted to the known units of the other side, and a third example that is probably the best practice of converting both sides of the comparison to a specific, known unit.
There are a few minor touch points in the test framework to deal with a bug I found where filenames were not being parsed correctly to extract the library name and version.
> Add test of the engine behavior for quantities of different UoM

- cohort-cli/src/test/java/com/ibm/cohort/cli/MeasureCLITest.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/MeasureEvaluator.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/MeasureEvaluatorTest.java
- tests/src/main/resources/measureCLIExample-separate-measure-server.json
Make the MeasureEvaluator always return a MeasureReport even when an individual is not in the initial population. Update unit tests and Taurus tests to expect the previously filtered reports.
> Wffhcohort 273 - Return MeasureReports even when not in the intitial population

- cohort-engine/README.md
User Guide link was still pointing to https://pages.github.ibm.com, switched to https://alvearie.github.io.
> Update README.md for cohort-engine

- Dockerfile
- cohort-engine-distribution/pom.xml
- cohort-engine-distribution/src/main/assembly/distribution.xml
Small change to add the shaded cli engine jar to our dockerfile so that the test test can execute tests against it during the toolchain. I added the jar to our distribution tar.gz that gets created by the maven build, and then added it to the dockerfile
> Added shaded jar to dockerfile

- cohort-engine-api/.gitignore
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/RestFhirLibraryResolutionProvider.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/BaseMeasureTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/MeasureEvaluatorTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/RestFhirLibraryResolutionProviderTest.java
Kwas noticed that after my recent PR to address measure resource resolution tasks we were getting an extra round trip to the FHIR server for each Library associated with a measure. This patch updates the caching implementation to avoid the extra hit. I also added a .gitignore file to cohort-engine-api to avoid some extraneous build artifacts from showing up as changes. See the individual commit messages for complete details.
> Fix extra round trip to FHIR server during Measure evaluation Library load step.

- docs/dev-guide/_sidebar.md
- docs/dev-guide/spikes/cql-fhir-parameter-investigation.md
_covers_ type support and gaps when converting from `FHIR` to `cql` data types.
> add spike docs for measure parameter model

- chart/cohort/templates/deployment.yaml
This change implements the k8s liveness/readiness and startup probes. I picked values that seemed reasonable to me and were comparable to other implementations I check that were also running liberty servers.
From the k8s documentation:
The kubelet uses liveness probes to know when to restart a container. For example, liveness probes could catch a deadlock, where an application is running, but unable to make progress. Restarting a container in such a state can help to make the application more available despite bugs.
The kubelet uses readiness probes to know when a container is ready to start accepting traffic. A Pod is considered ready when all of its containers are ready. One use of this signal is to control which Pods are used as backends for Services. When a Pod is not ready, it is …
> Wffhcohort 290 cloud readiness liveness

- cohort-engine-api-web/src/main/java/com/ibm/cohort/engine/api/service/CohortServiceExceptionMapper.java
when an `FHIR`-side error occurs
`BaseServerResponseException::getResponseBody` contains more details regarding why the error occurred.
_per discussion in [#cohorting-backend](https://ibm-watsonhealth.slack.com/archives/C01922MH1EY/p1615907830006800)_
> return FHIR exception details in endpoint requests

- cohort-parent/pom.xml
Followed this plugin's recommendation to use "jar-no-fork" as more appropriate within the build lifecycle: https://maven.apache.org/plugins/maven-source-plugin/usage.html.
There *should* be no additional work to get these into github packages on publish, but I will confirm that after merge.
> Adding source jars to build

- cohort-parent/pom.xml
Needed to exclude this dependency for an Appscan issue. Updating the version did not resolve the issue (resolution in the appscan issue was not worded clearly).
> Exclude dependency for appscan vulnerability

- cohort-engine/src/test/java/com/ibm/cohort/engine/CqlEngineWrapperTest.java
- cohort-engine/src/test/resources/cql/temporal/IntervalStartsInterval-1.0.0.cql
It was noted that the CQL Author's Guide lists "interval begins
interval" as a valid operator, but it wasn't functioning in the engine.
After investigation, it was determined to be a documentation problem.
The correct operation is "interval starts interval". This unit test
validates that operator exists and is functional.
> Add unit test for "interval starts interval"

- Dockerfile
Changed to use openly available base images that have been approved by security after review with our security focal. Also updated our liberty version to 21.0.0.3 since it was the latest available.
> Wffhcohort 344 open source base images

- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/MeasureParameterInfoList.java
The JsonProperty annotation was causing the swagger ui to improperly display the name of the parameter list in the results returned from the API call.
> Swagger UI fix

- cohort-engine-api-web/src/main/java/com/ibm/cohort/engine/api/service/CohortEngineRestHandler.java
- docs/user-guide/_sidebar.md
I brought these over from my PR for WFFHCOHORT-355 since it isn't clear
that is going to make R1 and we would like to include these as part of
the release. This includes updates to the swagger for the /evaluation 
REST API and the addition of the parameter formats page to the 
sidebar in the user guide.
> Doc updates in Swagger for the evaluation API and the user guide.

- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/CDMMeasureEvaluation.java
Sonar was flagging this as a bug, removed always failing null check.
https://sonarcloud.io/project/issues?id=Alvearie_quality-measure-and-cohort-service&open=AXkz1pjGGbJmCi2yRODy&resolved=false&types=BUG
> Sonar "bug"

- cohort-cli/src/main/java/com/ibm/cohort/cli/CohortCLI.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/CqlEvaluator.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/ExpressionResultCallback.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/BasePatientTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/CqlEvaluatorTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/CqlTemporalTests.java
- docs/user-guide/getting-started.md
- tests/src/main/java/com/ibm/cohort/engine/test/TestWrapper.java
As discussed in the team call, renaming the public API for consistency with the MeasureEvaluator and to just be a better name.
> Rename CqlEngineWrapper to CqlEvaluator

- cohort-cli/src/test/resources/cql/result-types/test_result_types.cql
- cohort-engine/src/main/java/com/ibm/cohort/engine/translation/InJVMCqlTranslationProvider.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/translation/CqlTranslatorProviderTest.java
- cohort-engine/src/test/resources/cql/failure/exception.cql
Pretty simple change.  Added an "error" and "exception" test case.
The only "exception only" test case I have run into is not including `FHIRHelpers` when it's needed.
This change actually revealed that one of our test measures did not include `FHIRHelpers` when it should have.
> WFFHCOHORT-413: Check for CQL Translation Exceptions

- chart/cohort/Chart.yaml
- pipeline.config
- prePromotion.sh
- tests/run-tests.sh
Updated version in Helm chart, added prePromotion.sh script which checks the version files and removes the tests we don't want to run when deploying into a cluster that doesn't have a fhir server with our test data loaded. Added a dummy test script used to produce fake results to keep the toolchain happy when run by consumers.
> R1 promotion updates

- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/ResourceResolutionProvider.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/ResourceResolutionProviderTest.java
- cohort-util/src/main/java/com/ibm/cohort/version/SemanticVersion.java
- cohort-util/src/test/java/com/ibm/cohort/version/SemanticVersionTest.java
Change logic in ResourceResolutionProvider.java to index resources no matter the version string (previously threw an error if version was not a semantic version).
When retrieving resources and not providing a version to use during the retrieval, only consider resources with semantic versions when calculating the latest version. When a version is provided, attempt an exact match using the provided version.
> Allow non-semantic version strings for resources

- cohort-engine/src/main/java/com/ibm/cohort/engine/cqfruler/MeasureEvaluation.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/cqfruler/MeasureEvaluationTest.java
ports over the changes in [DBCG/cqf-ruler#154](https://github.com/DBCG/cqf-ruler/pull/154/files#diff-2ba2e6fa2865691c2557d753dd53f08a88e3294d3cb84f70f6a5f66119efc8f3)
not exactly sure this is the best way to handle this,
but with so much code being copied over, this was the least intrusive change.
---
as Corey mentioned, the ability to use `setAccessible` won't work going into java 11,
so I also opened up a PR in https://github.com/DBCG/cql_engine/pull/494 to expose that functionality.
---
> apply expression cache clear patch from cql-ruler

- terraform/versions.tf
version is published that doesn't work with the backlevel version of
terraform the toolchains are using
> explicitly specify provider versions to avoid being broken when a newer

- cohort-cli/src/main/java/com/ibm/cohort/cli/TranslationCLI.java
- cohort-engine/pom.xml
- cohort-engine/src/main/java/com/ibm/cohort/engine/CqlEvaluator.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/TranslatingLibraryLoader.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/elm/execution/OptimizedCqlLibraryReader.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/elm/execution/OptimizedObjectFactory.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/elm/execution/ShortAndEvaluator.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/elm/execution/ShortOrEvaluator.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/LibraryLoader.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/DirectoryLibrarySourceProviderTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/ZipStreamLibrarySourceProviderTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/elm/execution/OptimizedCqlLibraryReaderTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/elm/execution/OptimizedObjectFactoryTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/elm/execution/ShortCircuitEvaluatorTest.java
- cohort-parent/pom.xml
- cohort-translation/pom.xml
- cohort-translation/src/main/java/com/ibm/cohort/translator/provider/BaseCqlTranslationProvider.java
- cohort-translation/src/main/java/com/ibm/cohort/translator/provider/CqlTranslationProvider.java
- cohort-translation/src/main/java/com/ibm/cohort/translator/provider/InJVMCqlTranslationProvider.java
- cohort-translation/src/main/resources/com/ibm/cohort/translator/optimization/jaxb.properties
- cohort-translation/src/test/java/com/ibm/cohort/translator/provider/CqlTranslatorProviderTest.java
- cohort-translation/src/test/resources/cql/basic/test.xml
While working with the health patterns team, I found that the
CqlEvaluator interface was inconsistent with regard to the APIs exposed
for CqlEvaluationResult and CqlExpressionResult callbacks. I added a few
signatures so that we have consistency.
While I was working, I noticed that the split of the
CqlTranslationProvider into its own project moved some code into the
translator project that did not technically belong to the translator.
The translator produces ELM in an execution agnostic ELM format, the CQL
Engine consumes that ELM and maps it into an execution typesystem. The
custom object factory code is only needed on the execution side and not
the translation side. I moved the OptimizedCqlLibraryReader and its
related classes back into the cohort-engine project where they started.
This …
> API updates for CqlEvaluator and ELM deserialization

- Dockerfile
- chart/cohort/Chart.yaml
- chart/cohort/templates/_helpers.tpl
- chart/cohort/templates/cohort/deployment.yaml
- chart/cohort/templates/cohort/service.yaml
- chart/cohort/templates/spark-history-server/deployment.yaml
- chart/cohort/templates/spark-history-server/service.yaml
- chart/cohort/values.yaml
- docker/spark-history-server/Dockerfile
- docker/spark-history-server/entrypoint.sh
- pipeline.config
There are a couple of toolchain-specific reasons things are set up this way that my notes on [Confluence](https://confluence.wh-sdlc.watson-health.ibm.com/pages/viewpage.action?pageId=69960134) cover in a bit more detail.
Still, these changes get us the base things we want for now (with the possibility of splitting/moving the components to different repositories in the future).
* _Add_ `Dockerfile` for spark history server based on [base spark image setup](https://confluence.wh-sdlc.watson-health.ibm.com/pages/viewpage.action?spaceKey=COH&title=Spark+Base+Dockerfile). 
* _Add_ spark history server deployment, with an overridable feature flag (`sparkHistoryServer.enabled`).
* _Update_ toolchain to use  `hadolint` for parsing `Dockerfile`s: allows for inline comments within commands.
* …
> Add spark history server build and deployment

- chart/cohort/templates/spark-history-server/deployment.yaml
- chart/cohort/values.yaml
I updated the Spark History Server deployment to use values from the newly formatted `spark-cos-secret` that is based on the IBM S3 FS plugin. We don't have endpoint ID as part of that secret, so it needed to come from somewhere else. I set a default value of the US geography endpoint with the assumption that the CD deployment pipeline will override to set whatever is truly used in the deployment environment. As part of that, I updated the overrides files in the cohorting-config repo. This was tested in cicdtest and works.
> Update spark-history-server to use latest spark-cos-secret contents

- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/SparkCqlEvaluator.java
- cohort-evaluator-spark/src/test/java/com/ibm/cohort/cql/spark/SparkCqlEvaluatorTest.java
- cohort-evaluator/src/main/java/com/ibm/cohort/cql/evaluation/CqlEvaluationRequest.java
- cohort-model-datarow/src/main/java/com/ibm/cohort/datarow/model/CodeKey.java
- cohort-model-datarow/src/test/java/com/ibm/cohort/datarow/model/CodeKeyTest.java
Filtering logic was happening, but the resulting object wasn't being passed through to the final  evaluate. I moved the logic to the final evaluate statement.
I'm not a huge fan of the extra method I added, but it made it easy to write tests quickly.
There was also a NullPointerException for the CodeKey class if System was null and equals was called. I added a test and a code fix.
> Filtering fix

- cohort-evaluator-spark/Dockerfile
- cohort-evaluator-spark/pom.xml
Spark includes hadoop-common which includes the JSP 2.1 API JAR. The JSP
2.1 API JAR has some javax.el API classes in it that are not compatible
with modern implementations of the EL classes. I had a choice to either
backlevel our javax.validation dependency to 4.2.1.Final and javax.el to
1.0.0.GA or increment our JSP version to 2.2. I went with the later.
This required an update to the Dockerfile to remove the JSP API version
included with the Spark distribution and some dependency management to
make sure we had the necessary JARs in the Spark application classpath.
Signed-off-by: Corey Sanders <corey.thecolonel@gmail.com>
> Fix expression language classpath issue in Spark App

- pipeline.config
Tested in a CIVALIDATE run and confirmed the sonar pods do not come back.
I will open PRs in other projects for the remaining CI toolchains that run in our cluster.
> Disable sonar in the toolchain

- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/FHIRRestUtils.java
- cohort-engine-api/src/test/java/com/ibm/cohort/engine/api/service/FHIRRestUtilsTest.java
Return readable json for the value of object-level parameters. I ended up settling on this implementation for now, as it will be the easiest to add other parameters types that might be needed in the future.
> Wffhcohort-587: Return defaultValues in readable format

- tests/scripts/validateSparkFvtOutput.py
This PR is to fix the python validation script used for validating results from spark-submit of the fvt tests. The FVT tests were failing due to the fact that prior to Corey's PR related to splitting output into multiple rows based on parameters, the script did not have to account for a parameters column in the output. Now that his PR has been merged down the validation is failing due to this missing column in the expected output. 
Signed-off-by: Jai D Goradia <goradia@us.ibm.com>
> Fix validation script for Spark tests to account for the new parameters column in the output

- prePromotion.sh
Additions to the prePromotion.sh script to allow the ability to push our spark docker image to the wh-common-rns (or other container registry). Script checks for presence of the env var required to contain the image name, pulls the image, and then pushes it to the configured container registry. I didn't do a ton of work to make some of the region, cloud url, etc. configurable because this is a short term fix until the 3.6.0 toolchain support is released, at which point, this code can be removed.
> Spark image promotion script updates

- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/SparkCqlEvaluator.java
- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/SparkCqlEvaluatorArgs.java
- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/metadata/EvaluationSummary.java
- cohort-evaluator-spark/src/test/java/com/ibm/cohort/cql/spark/SparkCqlEvaluatorTest.java
- cohort-evaluator-spark/src/test/resources/log4j.properties
Note: There are some spark log classes that don't accept the mdc property, such as TaskSetManager or certain scheduler logs. These logs don't look like they'd be particularly vital for everyday use (for example, `Registering RDD 5 (toString at String.java:2994) as input to shuffle 0` ), but I think it's important to keep in mind.
> Wffhcohort-738: Add correlation id to logging statements

- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/aggregation/ContextRetriever.java
I added this exception, then tried to write a test where it could ever be hit. I wasn't successful, and I don't think it would be possible to hit it. I could also move this exception to within gatherRDDs (throw IllegalState if it tries to return an empty list), they seemed about on par to me, though I could see someone preferring an empty list check at the end of a method rather than the beginning aesthetically. 
I also, while trying to experiment, ignored the error within sonarcloud that believed the list could be empty. I expected that the "bug" would come back if another branch produced the same issue, but that doesn't seem to be the case: https://sonarcloud.io/summary/new_code?branch=cql-spark-evaluator&id=Alvearie_quality-measure-and-cohort-service 
Personally, I think that since …
> WFFHCOHORT-706

- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/metadata/BaseOutputMetadataWriter.java
- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/metadata/HadoopPathOutputMetadataWriter.java
- The success marker file is created with a content to mitigate an issue in NiFi
> HIWHC-5353 NiFi not able to use _SUCCESS file with 0 byte

- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/JobStatus.java
- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/SparkCqlEvaluator.java
- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/errors/EvaluationError.java
- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/metadata/EvaluationSummary.java
- cohort-evaluator-spark/src/test/java/com/ibm/cohort/cql/spark/SparkCqlEvaluatorTest.java
- docs/user-guide/spark-user-guide.md
This PR makes it so the batch output summary is created even when `--halt-on-error` is used during a run. I would recommend ignoring whitespace in the diff for an easier time reviewing.
One thing to note about this change is that the accumulator used to track errors is not reported back to the driver when there is a failure. This is why I am catching any exception that is thrown and doing my best to get the message(s) out of the exception and into the `EvaluationSummary` object used to create the output report.
> Wffhcohort 700

- chart/cohort/templates/spark-history-server/deployment.yaml
- chart/cohort/values.yaml
- docker/spark-history-server/entrypoint.sh
Pass in the parameters needed to enable spark history server log cleanup.  SPARK_HISTORY_OPTS was already being set in the entrypoint.sh file called by the history server Dockerfile, so just needed to set the parms and pass them in via the helm chart.
> Wffhcohort 491 spark history log cleanup

- chart/cohort/values.yaml
Int.MaxValue (while listed in the documentation as the default, but apparently not to be put in literally) causes an exception in the history server on cleanup attempts after the first attempt (not sure why it work on the first attempt, but not subsequent ones). I had added it as informational so people would more easily see it as an option, but since it is causing a problem, I'm just removing it.
Signed-off-by: TimBishop <tabishop@us.ibm.com>
> Int.MaxValue was causing an exception in the spark history server.

- cohort-engine-api-web/launchers/cohort-engine-api-web-VT.launch
- cohort-engine-api-web/pom.xml
- cohort-engine-api-web/src/main/java/com/ibm/cohort/engine/api/service/CohortEngineRestHandler.java
- cohort-engine-api-web/src/main/java/com/ibm/cohort/engine/api/service/CohortEngineRestStatusHandler.java
- cohort-engine-api-web/src/main/java/com/ibm/cohort/engine/api/service/CohortServiceExceptionMapper.java
- cohort-engine-api-web/src/test/java/com/ibm/cohort/engine/api/service/CohortEngineRestHandlerTest.java
- cohort-engine-api-web/src/test/java/com/ibm/cohort/engine/api/service/CohortEngineRestStatusHandlerTest.java
- cohort-engine-api-web/src/test/java/com/ibm/cohort/engine/api/service/CohortHandlerBaseTest.java
- cohort-engine-api-web/src/test/java/com/ibm/cohort/engine/api/service/CohortServiceExceptionMapperTest.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/EnhancedHealthCheckInput.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/EnhancedHealthCheckResults.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/FhirServerConnectionStatusInfo.java
- cohort-engine-api/src/test/java/com/ibm/cohort/engine/api/service/model/EnhancedHealthCheckInputTest.java
- cohort-engine-api/src/test/java/com/ibm/cohort/engine/api/service/model/EnhancedHealthCheckResultsTest.java
Added new enhanced health check endpoint to the CohortEngineRestStatusHandler so it shows up under along side the other existing health check endpoints. Refactored a few classes to pull out some common test function. I added some custom exception checking because in certain cases the FHIR client hardcodes a 500 http status code and the authoring tool wanted to be able to distinguish timeout/failed connection/vs other problems so I added code to look for certain exceptions in the cause chain so I could set a specific error code in the errors we give back.
Below are some screenshots of the swagger interface to help illustrate how it will look:
> Wffhcohort 540 enhanced health check

- .github/workflows/build.yml
- cohort-engine/src/main/java/com/ibm/cohort/engine/r4/cache/R4FhirModelResolverFactory.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/FhirClientTimeoutTest.java
- cohort-evaluator-spark/src/test/java/com/ibm/cohort/cql/spark/BaseSparkTest.java
- cohort-evaluator-spark/src/test/java/com/ibm/cohort/cql/spark/aggregation/ContextRetrieverTest.java
- preDockerBuild.sh
This PR implements some of the build changes discussed during our standup. Primary changes are:
- Using the maven `-T` option to build modules in parallel.
- Using a shared `ModelResolver` in `R4FhirModelResolverFactory`.
- Lowering the timeouts in `FhirClientTimeoutTest`.
- Configuring fewer partitions in `BaseSparkTest` so that Spark tests create fewer tasks and run faster.
- Changing the number of partitions caused a sorting change in `ContextRetrieverTest`.
I ran these changes multiple times with both GitHub and our toolchain. GitHub builds sped up by about 2 min (about 6:06 maven build time). IBM Cloud builds sped up by about 4-5 min (about 15 min. maven build time).
> WFFHCOHORT-864 Build changes

- cohort-cli/pom.xml
- cohort-cli/src/main/java/com/ibm/cohort/cli/TranslationCLI.java
- cohort-cli/src/test/java/com/ibm/cohort/cli/TranslationCLITest.java
The `toString()` on the `Library` object was not human readable in the `TranslationCLI`. I made a change to just dump out the multi-line XML to the console so it should be easier to scroll through and be more human readable.
> Output multi-line xml in TranslationCLI

- cohort-cli/src/main/java/com/ibm/cohort/cli/CohortCLI.java
- cohort-engine-api-web/src/main/java/com/ibm/cohort/engine/api/service/CohortEngineRestHandler.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/BasePatientTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/CqlEvaluatorIntegrationTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/CqlTemporalTests.java
- cohort-evaluator/src/main/java/com/ibm/cohort/cql/evaluation/CqlContextFactory.java
- cohort-evaluator/src/main/java/com/ibm/cohort/cql/evaluation/CqlEvaluator.java
- cohort-evaluator/src/main/java/com/ibm/cohort/cql/library/CqlLibraryDescriptor.java
- cohort-evaluator/src/main/java/com/ibm/cohort/cql/library/CqlVersionedIdentifier.java
- cohort-evaluator/src/test/java/com/ibm/cohort/cql/evaluation/CqlContextFactoryTest.java
- cohort-evaluator/src/test/java/com/ibm/cohort/cql/evaluation/CqlEvaluatorTest.java
- cohort-model-datarow/src/test/java/com/ibm/cohort/datarow/engine/DataRowDataProviderTest.java
to use `CqlVersionedIdentifier` instead of `CqlLibraryDescriptor`
as the `format` field is not needed as a part of cohort evaluation
---
- [WFFHCOHORT-852: Remove the use of CqlLibraryDescriptor from CqlEvaluator](https://jira.wh-sdlc.watson-health.ibm.com/browse/WFFHCOHORT-852)
> Refactor `CqlEvaluator::evaluate` API

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- tests/src/main/python/TestDriver_CohortCLI.py
- tests/src/main/python/TestDriver_MeasureCLI.py
- tests/src/main/python/TestDriver_MeasurePerformance.py
I separated the workflows for the `Java` and `Python` analyses, just to get a bit of parallelism there.
I experimented with a few different [QL Packs](https://codeql.github.com/docs/codeql-cli/about-ql-packs/) and configurations
and felt that the `security-extended` suite made the most sense for now.
There were four existing "high" severity vulnerabilities that CodeQL picked up.
[Security > code-scanning](https://github.com/Alvearie/quality-measure-and-cohort-service/security/code-scanning?query=is%3Aopen+branch%3Asetup-codeql++)
Three of them were _Clear-text logging of sensitive information_ in various `python` test classes,
and the other flagged `SHA-256` as a "weak cryptographic algorithm" 
(but we are just using it to generate version ids, so I'm not sure there's a whole lot of risk …
> Setup CodeQL

- cohort-cli/src/test/java/com/ibm/cohort/cli/CohortCLITest.java
- cohort-cli/src/test/java/com/ibm/cohort/cli/MeasureCLITest.java
- cohort-cli/src/test/java/com/ibm/cohort/cli/TranslationCLITest.java
- cohort-engine-api-web/src/test/java/com/ibm/cohort/engine/api/service/CohortEngineRestHandlerTest.java
- cohort-engine-api-web/src/test/java/com/ibm/cohort/engine/api/service/CohortEngineRestStatusHandlerTest.java
- cohort-engine-api-web/src/test/java/com/ibm/cohort/engine/api/service/CohortHandlerTestBase.java
- cohort-engine-api/src/test/java/com/ibm/cohort/engine/api/service/FHIRRestUtilsTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/CqlEvaluatorIntegrationTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/CqlTemporalTests.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/FhirTestBase.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/PatientTestBase.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/cqfruler/MeasureSupplementalDataEvaluationTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/data/R4DataProviderFactoryTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/CDMMeasureEvaluationTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/FHIRClientContextTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/FhirClientTimeoutTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/MapFhirResourceResolverIntegrationTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/MeasureEvaluatorTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/MeasureHelperTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/MeasureTestBase.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/R4MeasureEvaluatorBuilderTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/RestFhirLibraryResolverIntegrationTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/RestFhirMeasureResolverIntegrationTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/retrieve/R4RestFhirRetrieveProviderTest.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/terminology/R4RestFhirTerminologyProviderTest.java
- cohort-evaluator-spark/src/test/java/com/ibm/cohort/cql/spark/SparkCqlEvaluatorTest.java
- cohort-util/src/main/java/com/ibm/cohort/valueset/ValueSetUtil.java
- fhir-resource-tooling/src/test/java/com/ibm/cohort/tooling/fhir/MeasureImporterTest.java
- fhir-resource-tooling/src/test/java/com/ibm/cohort/tooling/fhir/ValueSetImporterTest.java
See https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER&types=CODE_SMELL&id=Alvearie_quality-measure-and-cohort-service for smells.
Changes include
* Renaming test utility classes to not end in the word "Test", so they're not flagged as not having tests
* Adding assertions to some tests (if anyone has a better suggestion for what to test, please speak up)
* Removing the test flag from a method that exists only as one-time test data generation
* Adding a comment making it explicit that we're falling through a case statement, and adding a break
> Fixing sonar blocker codesmells

- cohort-evaluator-spark/pom.xml
- cohort-util/pom.xml
- cql-engine-addons/pom.xml
A couple pom updates to get the build to pass again. The first was updating the `poi` version in use to clear up the sonar issue. Once that change was made, then maven was flagging used undeclared dependencies. The `xml-apis` changes address that issue.
> Wffhcohort 928 - Update poi version

- cohort-engine/src/main/java/com/ibm/cohort/engine/data/R4DataProviderFactory.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/retrieve/RestFhirRetrieveProviderTest.java
- cohort-parent/pom.xml
And `CQF` from `1.5.6` → `1.5.8`
- https://github.com/DBCG/cql_engine/pull/513
> Updated Jackson and HAPI dependencies
- [WFFHCOHORT-863: Delete the cohort-engine Module](https://jira.wh-sdlc.watson-health.ibm.com/browse/WFFHCOHORT-863)
→ @dkwasny-ibm, lmk if you need any help merging this changeset into your branch.
* [Release v1.5.5 · DBCG/cql_engine](https://github.com/DBCG/cql_engine/releases/tag/v1.5.5)
* [Release v1.5.7 · cqframework/clinical_quality_language](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.5.7)
* [Release v1.5.8 · cqframework/clinical_quality_language](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.5.8)
* [WFFHCOHORT-930](https://jira.wh-sdlc.watson-health.ibm.com/browse/WFFHCOHORT-930)
> Upgrade CQL to `1.5.5`

- Dockerfile
- cohort-evaluator-spark/Dockerfile
- docker/spark-history-server/Dockerfile
Looks like these updates to ubi8 and liberty base image versions were sufficient to get past lastest set of vulnerabilities that are blocking successful run of our toolchains.
> Base image updates

- cohort-cli/src/main/java/com/ibm/cohort/cli/output/CqlEvaluationResultPrettyPrinter.java
- cohort-cli/src/test/java/com/ibm/cohort/cli/output/CollectionSizePrettyPrinterTest.java
- cohort-cli/src/test/java/com/ibm/cohort/cli/output/CqlEvaluationResultPrettyPrinterTest.java
- cohort-cli/src/test/java/com/ibm/cohort/cli/output/DisplayCollectionsPrettyPrinterTest.java
- cohort-parent/pom.xml
The FDA Best team was returning values wrapped in a Tuple when using the CohortCLI. Our code was only calling `Tuple.toString()` in that case, and that code was not properly displaying the nested fields inside of a `Tuple`.
This PR adds special handling for `Tuple` output so that each field is "pretty printed" rather than defaulting to the behavior of `toString()`.
I have shared the shaded jar with the FDA Best team and if they are satisfied with this change then I will merge back the code following any team feedback.
> Print out nested elements in Tuples
