Alvearie/quality-measure-and-cohort-service

- .gitignore
- cdm-modelinfo-tooling/pom.xml
- cohort-engine/pom.xml
- pom.xml
- tests/pom.xml
* Adding configuration for the flattener plugin
* Moving `dependencyManagement` info from `cohort-engine/pom.xml` to the parent pom
* Adding the `<scm>` block to all poms
> Misc POM improvements

- cohort-parent/pom.xml
If anyone knows of any other spots please let me know
> Updating copyright for new year

- .github/workflows/publish.yml
WFFHCOHORT-220, tested, publish succeeded with sonar step referring to java 11
> Update sonar to java 11

- docs/dev-guide/_sidebar.md
- docs/dev-guide/value-sets.md
resolves [WFFHCOHORT-207](https://jsw.ibm.com/browse/WFFHCOHORT-207)
> add docs for value sets

- docs/dev-guide/_sidebar.md
- docs/dev-guide/spikes/initial-performance-evaluation.md
_addresses_ [WFFHCOHORT-30](https://jsw.ibm.com/browse/WFFHCOHORT-30)
---
rendered preview: [deekim/quality-measure-and-cohort-service](https://deekim.github.io/quality-measure-and-cohort-service/#/dev-guide/spikes/initial-performance-evaluation)
> add intial performance metrics for measure engine

- cohort-engine-api-web/pom.xml
- cohort-engine-api-web/src/main/java/com/ibm/cohort/engine/api/service/CohortEngineRestHandler.java
- cohort-engine-api-web/src/main/java/com/ibm/cohort/engine/api/service/CohortServiceExceptionMapper.java
- cohort-engine-api-web/src/test/java/com/ibm/cohort/engine/api/service/CohortEngineRestHandlerTest.java
- cohort-engine-api-web/src/test/java/com/ibm/cohort/engine/api/service/CohortServiceExceptionMapperTest.java
- cohort-engine-api/pom.xml
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/FHIRRestUtils.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/MeasureParameterInfo.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/MeasureParameterInfoList.java
- cohort-engine-api/src/main/java/com/ibm/cohort/engine/api/service/model/ServiceErrorList.java
- cohort-engine-api/src/test/java/com/ibm/cohort/engine/api/service/FHIRRestUtilsTest.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/RestFhirLibraryResolutionProvider.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/RestFhirMeasureResolutionProvider.java
- cohort-parent/pom.xml
This PR adds 2 new REST endpoints to get the parameter information for a measure. The entry points in the code when a rest call is made are in CohortEngineRestHandler.getMeasureParametersById and CohortEngineRestHandler.getMeasureParameters
> Wffhcohort 133 restful api return parameters

- cohort-cli/src/main/java/com/ibm/cohort/cli/MeasureCLI.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/MeasureEvaluator.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/evidence/MeasureEvidenceOptions.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/measure/MeasureEvaluatorTest.java
- cohort-engine/src/test/resources/cql/fhir-measure/test-adult-males.cql
To get this API change in front of the IHE team ASAP, creating a PR with just the option for evidence.  Subsequent PR will result in supporting doing something with it.
> Measure Evidence Param

- cohort-cli/src/test/java/com/ibm/cohort/cli/CohortCLITest.java
- cohort-engine-flink-example/README.md
- cohort-engine-flink-example/pom.xml
- cohort-engine-flink-example/src/main/java/com/ibm/cohort/engine/flink/KafkaCommon.java
- cohort-engine-flink-example/src/main/java/com/ibm/cohort/engine/flink/KafkaInfo.java
- cohort-engine-flink-example/src/main/java/com/ibm/cohort/engine/flink/MeasureExecution.java
- cohort-engine-flink-example/src/main/java/com/ibm/cohort/engine/flink/execution/CohortEngineFlinkDriver.java
- cohort-engine-flink-example/src/main/java/com/ibm/cohort/engine/flink/execution/FHIRServerInfo.java
- cohort-engine-flink-example/src/main/java/com/ibm/cohort/engine/flink/input/InputProducer.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/CqlEngineWrapper.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/FhirLibraryLibrarySourceProvider.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/ProviderFactory.java
- cohort-engine/src/test/java/com/ibm/cohort/engine/BaseFhirTest.java
- cohort-parent/pom.xml
Not a whole lot to say here.
There's a few optimizations and changes in the core projects in addition to the new submodule.
> WFFHCOHORT-192: Adding an example flink driver

- cohort-cli/src/main/java/com/ibm/cohort/cli/input/MeasureConfiguration.java
- cohort-cli/src/main/java/com/ibm/cohort/cli/input/MeasureIdentifier.java
- cohort-cli/src/main/java/com/ibm/cohort/cli/input/Parameter.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/measure/RestFhirMeasureResolutionProvider.java
- cohort-parent/pom.xml
First pass at cutting back on the app scan flags
> Changes to remove unnecessary dependencies

- cohort-parent/pom.xml
Updating versions per the AppScan report.  After this, things get harder.
> Updating a couple versions of things for AppScan

- cohort-parent/pom.xml
Updated dependency versions for ASoC issues
> Wffhcohort 286 address appscan results

- cohort-cli/src/main/java/com/ibm/cohort/cli/MeasureCLI.java
- docs/user-guide/getting-started.md
Per Jai's feedback on tickets.
> Updating docs and making paramter descriptions better

- cohort-parent/pom.xml
See lines 457-459.  Was causing a warning on maven build.
> Removing duplicate dependency

- cohort-parent/pom.xml
Updating pom to address vulnerability https://nvd.nist.gov/vuln/detail/CVE-2021-22696
> PSIRT remediation

- cohort-engine-api-web/pom.xml
- cohort-parent/pom.xml
Just a couple open source version package updates needed for ASoC scans required for PSRB review.
> Updated versions to address ASoC vulnerabilities

- cohort-engine-api-web/src/main/java/com/ibm/cohort/engine/api/service/CohortEngineRestHandler.java
- cohort-util/src/main/java/com/ibm/cohort/valueset/ValueSetUtil.java
- cohort-util/src/test/java/com/ibm/cohort/valueset/ValueSetUtilTest.java
- cohort-util/src/test/resources/codeSystemOverride.txt
- docs/user-guide/getting-started.md
- fhir-resource-tooling/pom.xml
- fhir-resource-tooling/src/main/java/com/ibm/cohort/tooling/fhir/ValueSetImporter.java
Adding the ability to specify user-defined code systems by passing in a map of key to url. I'm making the assumption that we're never mapping a url to another url, and that if a user specifies a literal URL then that will be used as it is given. 
If we want a different format than key=value I'm open to that.
> WFFHCOHORT-303

- cohort-engine-api-web/src/main/java/com/ibm/cohort/engine/api/service/CohortEngineRestHandler.java
- cohort-engine-api-web/src/test/java/com/ibm/cohort/engine/api/service/CohortEngineRestHandlerTest.java
- cohort-engine-api-web/src/test/java/com/ibm/cohort/engine/api/service/vt/DefaultVT.java
- cohort-util/src/main/java/com/ibm/cohort/valueset/ValueSetUtil.java
This started as a rebase-fix, but Jeff requested 200 become 201, and Corey noticed the responses weren't parsing correctly in swagger, so here are those 3 fixes all together.
> Wffhcohort 303 fix

- cohort-parent/pom.xml
PSIRT found.  I'm not going to report it since this is only used in test and therefore couldn't be exploited, but figured I'd update it anyway.
> Updating Jetty for vulnerability

- chart/cohort/templates/deployment.yaml
- chart/cohort/values.yaml
- pipeline.config
- terraform/main.tf
- terraform/outputs.tf
- terraform/variables.tf
- terraform/versions.tf
- tests/run-engine-taurus-deploy.yaml
This PR contains the terraform changes to create the tls certs, and the deployment configuration changes needed to deploy to our vpc environment.
> Vpc rest service deployment

- cohort-engine-api-web/src/test/resources/expectedOutput/measure_evaluation_exp.json
Updating VTs for timezone changes
> Updating json for VTs

- chart/cohort/Chart.yaml
- pipeline.config
- prePromotion.sh
- tests/run-tests.sh
These are the same changes I put in the release branch to do the image promotion to the image repository and publish to the umbrella repo we would allow consumers to deploy from.
> Release promotion updates for main

- Dockerfile
Updated our base image to a later fixpack of websphere liberty
> Base image vulnerability fix

- pipeline.config
- terraform/variables.tf
- terraform/versions.tf
Some very small changes for the toolchain updates
> Toolchain version 342 updates

- build/pom.xml
- chart/cohort/Chart.yaml
- cohort-parent/pom.xml
Updated the version to 1.0.2-SNAPSHOT and updated some open source package versions
> Update version and oss packages

- build/src/main/resources/com/ibm/cohort/build/pmd-ruleset.xml
- cohort-engine/src/main/java/com/ibm/cohort/engine/cqfruler/MeasureEvaluation.java
- cohort-engine/src/main/java/com/ibm/cohort/engine/retrieve/R4RestFhirRetrieveProvider.java
- fhir-client-config/pom.xml
- fhir-client-config/src/main/java/com/ibm/cohort/fhir/client/config/DefaultFhirClientBuilder.java
Adding PMD rule that calls out size > 0 calls and recommends replacing them with CollectionUtils.isEmpty
> Wffhcohort-655

- .github/workflows/sonar_spark.yml
Adding a github workflow for sonar to run on the spark branch.
> Sonar spark

- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/SparkCqlEvaluator.java
- cohort-evaluator-spark/src/test/java/com/ibm/cohort/cql/spark/SparkCqlEvaluatorTest.java
- cohort-evaluator-spark/src/test/resources/alltypes/cql/NoFields-1.0.0.cql
- cohort-evaluator-spark/src/test/resources/alltypes/metadata/context-definitions-related-column.json
- cohort-evaluator-spark/src/test/resources/alltypes/metadata/join-only.json
Signed-off-by: matthew.sargent <matthew.sargent@ibm.com>
> WFFHCOHORT-701 Update logic for gathering join columns

- cohort-engine/src/main/java/com/ibm/cohort/engine/CqlEvaluator.java
- cohort-evaluator-spark/src/main/java/com/ibm/cohort/cql/spark/SparkCqlEvaluator.java
- cohort-evaluator-spark/src/test/java/com/ibm/cohort/cql/spark/SparkCqlEvaluatorTest.java
- cohort-evaluator-spark/src/test/resources/simple-job/cql-jobs-now.json
- cohort-evaluator-spark/src/test/resources/simple-job/cql/SampleLibrary-1.0.0.cql
- cohort-evaluator/src/main/java/com/ibm/cohort/cql/evaluation/CqlEvaluator.java
Signed-off-by: shelley.murphy <mshelley@us.ibm.com>
> Adding single batch time to evaluation process

- cohort-parent/pom.xml
Simple dependency version update
Signed-off-by: TimBishop <tabishop@us.ibm.com>
> Move dependency update from our 2.0.0 release so we are in sync

- tests/docker/taurus-bridge-portForwarding.dockerfile
- tests/run-engine-taurus-deploy.yaml
Signed-off-by: Rick Stevens <rstevens@us.ibm.com>
> Minor taurus docker image updates

- docs/user-guide/fhir-resource-tooling.md
- fhir-resource-tooling/pom.xml
- fhir-resource-tooling/src/main/java/com/ibm/cohort/tooling/cos/CosConfiguration.java
- fhir-resource-tooling/src/main/java/com/ibm/cohort/tooling/fhir/ValueSetImporter.java
- fhir-resource-tooling/src/main/java/com/ibm/cohort/tooling/s3/S3Configuration.java
- fhir-resource-tooling/src/test/java/com/ibm/cohort/tooling/fhir/ValueSetImporterTest.java
- fhir-resource-tooling/src/test/resources/example-cos-credentials.json
Adding option to write directly to COS, as well as or instead of the local file system.
> Wffhcohort 679 - add COS as possible storage location in fhir-resource-tooling

- cohort-parent/pom.xml
update rest service framework version to point to 1.1.0-SNAPSHOT
Signed-off-by: TimBishop <tabishop@us.ibm.com>
> point to updated rest service framework version

- cohort-evaluator-hapi-fhir/src/main/java/com/ibm/cohort/cql/hapi/resolver/R4QualityMeasureResolverFactory.java
- cohort-evaluator/src/main/java/com/ibm/cohort/cql/library/MapCqlLibraryProviderFactory.java
Doing a quick review of sonar showed these quick to fix "bugs".
https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER&types=CODE_SMELL&id=Alvearie_quality-measure-and-cohort-service&open=AXgX2idMqoMHQzLn4S_M
> Wrapping with try

- cohort-cli/pom.xml
- cohort-cli/src/test/java/com/ibm/cohort/cli/CohortCLITest.java
- cohort-cli/src/test/resources/cql/empty-context/EmptyContext-1.0.0.cql
- cohort-evaluator-spark/src/test/resources/any-column/cql/AnyColumnGrandChild-1.0.1.cql
- cohort-evaluator/pom.xml
- cohort-evaluator/src/main/java/com/ibm/cohort/cql/translation/CqlToElmTranslator.java
- cohort-evaluator/src/test/java/com/ibm/cohort/cql/translation/TranslatingCqlLibraryProviderTest.java
- cohort-evaluator/src/test/resources/cql/empty-context/EmptyContext-1.0.0.cql
- cohort-evaluator/src/test/resources/cql/empty-context/EmptyHelper-1.0.0.cql
- cohort-parent/pom.xml
- [WFFHCOHORT-353](https://jira.wh-sdlc.watson-health.ibm.com/browse/WFFHCOHORT-353)
> Prevent null CQL contexts

- terraform/modules/tls_cert/outputs.tf
- terraform/modules/tls_cert/tls_cert.tf
- terraform/versions.tf
This PR fixes the CSR issues we were hitting in the toolchain after our cluster was updated.
> Wffhcohort 895 - Fix csr creation for cohort service

- cohort-parent/pom.xml
Signed-off-by: Rick Stevens <rstevens@us.ibm.com>
> Updates to ossindex exclusions
